### ISSUE TITLE
sub-dependencies

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/importly#20]
it sucks having to install all of your dependencies' own dependencies

importly needs to take care of these, and include them into the importmap

here are some possible implementation directions

1. use `package.lock` instead of package.json
2. recurse over package jsons
3. use some npm faculty to obtain the graph

**Comment by trusktr** [comment]
Another idea is, because `import`s are supposed to be statically analyzable, can we just scan for `import` syntax (and map those based on Node.js module resolution)? If we do that, what about `import()` functions?

**Comment by trusktr** [comment]
Meteor and Rollup have support `import()` function, but only work with direct strings like `import('foo')` and not `import(magicVariable)`. Unfortunately (or not?) the web decided to let `import()` be dynamic (`import(anyString)`).

Maybe it'd be reasonable to allow importly to work with `import('string-literal')`, and otherwise document a caveat about the non-static form.

**Comment by chase-moskal** [comment]
@trusktr — i really love this idea!

it would be really cool if importly could operate on source code alone, and not require npm at all

the downside that gives me hesitation, is that it would be hard to find all subdependencies
- you mentioned following node module resolution, but that presupposes node_modules and package.json's anyways, so the user might as well use importly with their package.json
- we'd have to crawl all of the source code of all subdependencies, straight off the cdn's like jsdelivr or unpkg — i'm worried the implementation might be complicated and also run quite slowly
- and like you mentioned, dynamic imports would be an issue; whereas with the current package.json implementation, these are included properly as subdependencies and es-module-shims can interpret the dynamic imports

however if we could get it working, it would be super attractive for importly to operate on code alone and not require the user to use a package.json

without a breaking change, i think we could trigger this alternative mode if the user provides a directory argument
- `importly < package.json > importmap.json`
- `importly source > importmap.json` ← *new mode*

or alternatively supply a separate cli just for this experimental mode, `importlycode` or something

i don't have the gas to make this implementation, but if somebody else would like to hazard a prototype implementation in a pull request, i'd be interested to merge it

&nbsp; :wave: chase

**Comment by trusktr** [comment]
:wave: :)

Good points. I suppose if the code imports are scanned (as opposed to looking package.json of all sub-dependency in the tree), it could eliminate some dependencies from being placed in the import map because they weren't detected in the import maps.

But yeah, it would still be indirectly tied to NPM/Node.js node_modules.

> straight off the cdn's like jsdelivr or unpkg

Yeah, that's a bit tricky, because the source from those CDNs might have bare specifiers too. If people are importing those things, they may not be listed in package.json either. With high-speed internet, it may not be much of a problem, and the result could be cached.

> it would be super attractive for importly to operate on code alone

True! But without specific ties to node.js resolution, I'm not sure it would be feasible. There'd be expectations on a certain module resolution.

Maybe it would need an option like `importly source.js --resolution node > importmap.json`?
