### ISSUE TITLE
feature request: read package.json main fields in sub-folders.

### ISSUE THREAD

**Issue by trusktr** [chase-moskal/importly#21]
Some packages use package.json files in sub folders to create import aliases.

For example, here's a folder in Solid.js that contains only a package.json: https://github.com/ryansolid/solid/tree/61aa26ee6fa7fec07daa34068d9c8c7f6442d10f/dom

This allows someone using an environment with Node-style resolution to `import {...} from 'solid-js/dom'` although there is no actual source code in that folder. The node resolution looks up the main field in the package.json of that folder.

It'd be sweet if importly also handled such cases, adding those aliases to the import map.

**Comment by chase-moskal** [comment]
my initial thought was that we could support this by adding a `--node-resolution` flag or something that scans your local `node_modules` and attempts to emulate node resolution (though importly doesn't rely on npm or node_modules, so it would take considerable work)

however, i started thinking about how this kind of node resolution should probably be viewed as an old-fashioned common-js node-specific idiosyncratic vestige with no clear benefits, and so we want to deprecate its usage

instead of supporting node resolution, i think there's a better solution here for us

**when dealing with traditional node-resolution-oriented packages like solid-js:**
- never use node-resolution module identifiers (not supported by esm)
  ```js
  // no no
  import {render} from "solid-js/dom"
  ```
- always use esm module identifiers, and import javascript files directly
  ```js
  // yes yes
  import {render} from "solid-js/dist/dom/index.js"
  ```

**when maintaining a modern javascript library:**
- publish only modern esm code
- do not rely on any node resolution rules.. simply remove silly extra `package.json` or `index.js` files
- consumers simply import the modules they need, no need to re-route them around with aliases and confusing indirection

ultimately, with importly, i think we're aiming to deprecate our usage of old patterns, and wholly embrace the esm ecosystem

considering the above workaround, i think it's probably best for importly not to emulate node resolution — does this workaround satisfy your use-case, or do you think there is more about this issue worth thinking about?

@trusktr, please let me know what you think

thanks for contributing this issue!

👋 chase

**Comment by chase-moskal** [comment]
as a side-note i always thought it'd be cool for importly extensions to simply be more tools which can operate on the importmap.json, so they can be piped together

maybe something like an `importly-alias` tool could be used to add simple aliases

```bash
importly < package.json \
  | importly-alias \
    -a "solid-js/dom → solid-js/dist/dom/index.js" \
    -a "solid-js/html → solid-js/dist/dom/html.js" \
  > importmap.json
```

**Comment by trusktr** [comment]
About the import-alias idea, I may as well just write those aliases myself in a second import map instead of in a shell script; that's easy enough.

But I agree, it would be better to drop the old node-resolution and encourage good esm practices.
